function getExternalContractList(req, res) {
  setTimeout(() => {
    return res.json({
      "data": [
        {
          "prepaid_id": null,
          "prepaid_right_id": null,
          "is_master": null,
          "album_id": "537",
          "release_country_id": "229",
          "country_name_zh": "台灣",
          "album_disc_id": "458",
          "album_disc_content_id": "8972",
          "song_code": "bsc011805",
          "song_name": "想戀一個愛",
          "author_code": "bacs00114",
          "song_right_id": "4201",
          "song_rights": "改編詞(0.000)",
          "author": "陳勇志(陳勇志)",
          "is_digital": "1",
          "is_entity": "1",
          "contract_song_id": null,
          "contract_song_code": "SA",
          "is_effective": "1",
          "is_settled": "0",
          "is_paid": "0",
          "is_no_commission": "0",
          "value": null,
          "balance": null,
          "other_rights": [
            {
              "prepaid_id": null,
              "prepaid_right_id": null,
              "is_master": null,
              "album_id": "178",
              "album_code": "MOD-0002-CH",
              "release_country_id": "229",
              "country_name_zh": "台灣",
              "album_disc_id": "854",
              "disc": "Disc1(影片)",
              "album_disc_content_id": "8970",
              "song_code": "bsc011805",
              "song_name": "想戀一個愛",
              "song_rights_id": "4201",
              "song_rights": "改編詞(0.000)",
              "author": "陳勇志(陳勇志)",
              "is_effective": "1",
              "contract_song_id": null,
              "contract_song_code": "SA"
            },
            {
              "prepaid_id": null,
              "prepaid_right_id": null,
              "is_master": null,
              "album_id": "419",
              "album_code": "BM0009",
              "release_country_id": "229",
              "country_name_zh": "台灣",
              "album_disc_id": "664",
              "disc": "Disc1(CD)",
              "album_disc_content_id": "8971",
              "song_code": "bsc011805",
              "song_name": "想戀一個愛",
              "song_rights_id": "4201",
              "song_rights": "改編詞(0.000)",
              "author": "陳勇志(陳勇志)",
              "is_effective": "1",
              "contract_song_id": null,
              "contract_song_code": "SA"
            },
            {
              "prepaid_id": null,
              "prepaid_right_id": null,
              "is_master": null,
              "album_id": "538",
              "album_code": "BD0091",
              "release_country_id": "229",
              "country_name_zh": "台灣",
              "album_disc_id": "457",
              "disc": "Disc1(CD)",
              "album_disc_content_id": "8973",
              "song_code": "bsc011805",
              "song_name": "想戀一個愛",
              "song_rights_id": "4201",
              "song_rights": "改編詞(0.000)",
              "author": "陳勇志(陳勇志)",
              "is_effective": "1",
              "contract_song_id": null,
              "contract_song_code": "SA"
            },
            {
              "prepaid_id": null,
              "prepaid_right_id": null,
              "is_master": null,
              "album_id": "729",
              "album_code": "88985313282",
              "release_country_id": "97",
              "country_name_zh": "香港",
              "album_disc_id": "198",
              "disc": "Disc1(CD)",
              "album_disc_content_id": "8974",
              "song_code": "bsc011805",
              "song_name": "想戀一個愛",
              "song_rights_id": "4201",
              "song_rights": "改編詞(0.000)",
              "author": "陳勇志(陳勇志)",
              "is_effective": "1",
              "contract_song_id": null,
              "contract_song_code": "SA"
            },
            {
              "prepaid_id": null,
              "prepaid_right_id": null,
              "is_master": null,
              "album_id": "730",
              "album_code": "88985309242",
              "release_country_id": "97",
              "country_name_zh": "香港",
              "album_disc_id": "197",
              "disc": "Disc1(CD)",
              "album_disc_content_id": "8975",
              "song_code": "bsc011805",
              "song_name": "想戀一個愛",
              "song_rights_id": "4201",
              "song_rights": "改編詞(0.000)",
              "author": "陳勇志(陳勇志)",
              "is_effective": "1",
              "contract_song_id": null,
              "contract_song_code": "SA"
            }
          ],
          "other_rights_count": 5,
          "merge_rights": []
        }
      ],
      "execution_time": "0.1149",
      "memory_usage": "3.5MB",
      "status_code": "00000000",
      "params": {
        "album_disc_content_id": "8972"
      }
    });
  }, 1000);
}

function getInternalContractList(req, res) {
  setTimeout(() => {
    return res.json({
      "data": [
        {
          "prepaid_id": null,
          "prepaid_right_id": null,
          "is_master": null,
          "album_id": "537",
          "release_country_id": "229",
          "country_name_zh": "台灣",
          "album_disc_id": "458",
          "album_disc_content_id": "8972",
          "song_code": "bsc011805",
          "song_name": "想戀一個愛",
          "author_code": "bacs00594",
          "song_right_id": "4193",
          "song_rights": "曲(16.666)",
          "author": "Daniel Denholm(Daniel Denholm)",
          "is_digital": "1",
          "is_entity": "1",
          "contract_song_id": "187",
          "contract_song_code": "O-EMI-BEC",
          "is_effective": "1",
          "is_settled": "0",
          "is_paid": "0",
          "is_no_commission": "0",
          "is_limited": null,
          "value": null,
          "balance": null
        },
        {
          "prepaid_id": null,
          "prepaid_right_id": null,
          "is_master": null,
          "album_id": "537",
          "release_country_id": "229",
          "country_name_zh": "台灣",
          "album_disc_id": "458",
          "album_disc_content_id": "8972",
          "song_code": "bsc011805",
          "song_name": "想戀一個愛",
          "author_code": "bacs00593",
          "song_right_id": "4194",
          "song_rights": "曲(16.666)",
          "author": "Slot Machine(Slot Machine)",
          "is_digital": "1",
          "is_entity": "1",
          "contract_song_id": "187",
          "contract_song_code": "O-EMI-BEC",
          "is_effective": "1",
          "is_settled": "0",
          "is_paid": "0",
          "is_no_commission": "0",
          "is_limited": null,
          "value": null,
          "balance": null
        },
        {
          "prepaid_id": null,
          "prepaid_right_id": null,
          "is_master": null,
          "album_id": "537",
          "release_country_id": "229",
          "country_name_zh": "台灣",
          "album_disc_id": "458",
          "album_disc_content_id": "8972",
          "song_code": "bsc011805",
          "song_name": "想戀一個愛",
          "author_code": "bacs00592",
          "song_right_id": "4195",
          "song_rights": "曲(16.666)",
          "author": "Po Posayanukul(Po Posayanukul)",
          "is_digital": "1",
          "is_entity": "1",
          "contract_song_id": "187",
          "contract_song_code": "O-EMI-BEC",
          "is_effective": "1",
          "is_settled": "0",
          "is_paid": "0",
          "is_no_commission": "0",
          "is_limited": null,
          "value": null,
          "balance": null
        },
        {
          "prepaid_id": null,
          "prepaid_right_id": null,
          "is_master": null,
          "album_id": "537",
          "release_country_id": "229",
          "country_name_zh": "台灣",
          "album_disc_id": "458",
          "album_disc_content_id": "8972",
          "song_code": "bsc011805",
          "song_name": "想戀一個愛",
          "author_code": "bacs00592",
          "song_right_id": "4196",
          "song_rights": "詞(50.000)",
          "author": "Po Posayanukul(Po Posayanukul)",
          "is_digital": "1",
          "is_entity": "1",
          "contract_song_id": "187",
          "contract_song_code": "O-EMI-BEC",
          "is_effective": "1",
          "is_settled": "0",
          "is_paid": "0",
          "is_no_commission": "0",
          "is_limited": null,
          "value": null,
          "balance": null
        },
        {
          "prepaid_id": null,
          "prepaid_right_id": null,
          "is_master": null,
          "album_id": "537",
          "release_country_id": "229",
          "country_name_zh": "台灣",
          "album_disc_id": "458",
          "album_disc_content_id": "8972",
          "song_code": "bsc011805",
          "song_name": "想戀一個愛",
          "author_code": "bacs00593",
          "song_right_id": "4197",
          "song_rights": "曲(16.660)",
          "author": "Slot Machine(Slot Machine)",
          "is_digital": "1",
          "is_entity": "1",
          "contract_song_id": "177",
          "contract_song_code": "B-P-SlotMachine-2016",
          "is_effective": "0",
          "is_settled": "0",
          "is_paid": "0",
          "is_no_commission": "0",
          "is_limited": null,
          "value": null,
          "balance": null
        },
        {
          "prepaid_id": null,
          "prepaid_right_id": null,
          "is_master": null,
          "album_id": "537",
          "release_country_id": "229",
          "country_name_zh": "台灣",
          "album_disc_id": "458",
          "album_disc_content_id": "8972",
          "song_code": "bsc011805",
          "song_name": "想戀一個愛",
          "author_code": "bacs00592",
          "song_right_id": "4198",
          "song_rights": "曲(16.660)",
          "author": "Po Posayanukul(Po Posayanukul)",
          "is_digital": "1",
          "is_entity": "1",
          "contract_song_id": "176",
          "contract_song_code": "B-P-PoPosayanukul-2016",
          "is_effective": "0",
          "is_settled": "0",
          "is_paid": "0",
          "is_no_commission": "0",
          "is_limited": null,
          "value": null,
          "balance": null
        },
        {
          "prepaid_id": null,
          "prepaid_right_id": null,
          "is_master": null,
          "album_id": "537",
          "release_country_id": "229",
          "country_name_zh": "台灣",
          "album_disc_id": "458",
          "album_disc_content_id": "8972",
          "song_code": "bsc011805",
          "song_name": "想戀一個愛",
          "author_code": "bacs00592",
          "song_right_id": "4199",
          "song_rights": "詞(50.000)",
          "author": "Po Posayanukul(Po Posayanukul)",
          "is_digital": "1",
          "is_entity": "1",
          "contract_song_id": "176",
          "contract_song_code": "B-P-PoPosayanukul-2016",
          "is_effective": "0",
          "is_settled": "0",
          "is_paid": "0",
          "is_no_commission": "0",
          "is_limited": null,
          "value": null,
          "balance": null
        },
        {
          "prepaid_id": null,
          "prepaid_right_id": null,
          "is_master": null,
          "album_id": "537",
          "release_country_id": "229",
          "country_name_zh": "台灣",
          "album_disc_id": "458",
          "album_disc_content_id": "8972",
          "song_code": "bsc011805",
          "song_name": "想戀一個愛",
          "author_code": "bacs00594",
          "song_right_id": "4200",
          "song_rights": "曲(16.660)",
          "author": "Daniel Denholm(Daniel Denholm)",
          "is_digital": "1",
          "is_entity": "1",
          "contract_song_id": "175",
          "contract_song_code": "B-P-DanielDenholm-2016",
          "is_effective": "0",
          "is_settled": "0",
          "is_paid": "0",
          "is_no_commission": "0",
          "is_limited": null,
          "value": null,
          "balance": null
        }
      ],
      "execution_time": "0.1249",
      "memory_usage": "3.51MB",
      "status_code": "00000000",
      "params": {
        "album_disc_content_id": "8972"
      }
    });
  }, 1000);
}

function updateData(req, res) {
  setTimeout(() => {
    return res.json({});
  }, 1000);
}

export default {
  'get   /album_prepaid/external_contract': getExternalContractList,
  'get   /album_prepaid/internal_contract': getInternalContractList,
  'post  /album_prepaid/delete': updateData,
}