function getList(req, res) {
  const returnObj = {
    "data": {
      "total_cnt": 2,
      "data_list": [
        {
          "id": "2",
          "need_sign_back": "1",
          "author_phase_id": "107",
          "author_phase": "2020/01/01-2020/06/30",
          "song_phase_id": "105",
          "song_phase": "2019/10/01-2020/03/31",
          "contract_code": "yooooo",
          "name": "asdasd",
          "our_contract_code": "3345678",
          "receivable_phase": "1",
          "income_source": "2",
          "currency_id": "2",
          "exchange_rate": "4.53",
          "holder_company_id": "8",
          "holder_company_name": "EMI MS. PUB. (S.E.ASIA) Ltd., Taiwan Branch",
          "user_company_id": "1",
          "sold_date": "2020-11-06",
          "issued_date": "2020-11-06",
          "start_date": "2020-11-06",
          "end_date": "2020-11-06",
          "expiration_date": "2020-11-06",
          "contract_month": "15",
          "is_permanent": "0",
          "is_exclusive": "0",
          "authorized_area_type": "1",
          "authorized_area_id": "1",
          "note1": "0",
          "note2": "0",
          "note3": "0",
          "tax_rate": "6"
        },
        {
          "id": "7",
          "need_sign_back": "1",
          "author_phase_id": "5",
          "author_phase": "2009/07/01-2009/12/31",
          "song_phase_id": "5",
          "song_phase": "2009/07/01-2009/12/31",
          "contract_code": "miscASDTS",
          "name": "asdasd",
          "our_contract_code": "ASDVFGAS",
          "receivable_phase": "1",
          "income_source": "2",
          "currency_id": "4",
          "exchange_rate": "1.00",
          "holder_company_id": "8",
          "holder_company_name": "EMI MS. PUB. (S.E.ASIA) Ltd., Taiwan Branch",
          "user_company_id": "1",
          "sold_date": "2020-11-06",
          "issued_date": "2020-11-06",
          "start_date": "2020-11-06",
          "end_date": "2020-11-06",
          "expiration_date": "2020-11-06",
          "contract_month": "15",
          "is_permanent": "0",
          "is_exclusive": "0",
          "authorized_area_type": "3",
          "authorized_area_id": "1",
          "note1": "0",
          "note2": "0",
          "note3": "0",
          "tax_rate": "6"
        }
      ]
    },
    "execution_time": "0.1955",
    "memory_usage": "3.79MB",
    "status_code": "00000000",
    "params": {
      "keyword": "",
      "precise": "0",
      "phase_type": "0",
      "phase_start": "",
      "phase_end": "",
      "page_current": "1",
      "page_size": "20"
    }
  };

  return res.json(returnObj);
}

function getInfo(req, res) {
  const returnObj = {
    "data": {
      "data_list": {
        "id": "2",
        "need_sign_back": "1",  // 合約回覆
        "author_phase_id": "107",  // 詞曲計算期別
        "author_phase": "2020/07/01-2020/12/31",
        "song_phase_id": "105",  // 錄音計算期別
        "song_phase": "2019/10/01-2020/03/31",
        "contract_code": "yooooo",  // 合約編號
        "name": "asdasd",  // 產品標題
        "our_contract_code": "3345678",  // 我方紙本合約編號
        "receivable_phase": "1",  // 收款期別
        "income_source": "2",  // 收入來源
        "currency_id": "2",  // 幣別
        "exchange_rate": "4.53",  // 匯率
        "holder_company_id": "8",  // 權利人
        "holder_company_name": "EMI MS. PUB. (S.E.ASIA) Ltd., Taiwan Branch",
        "holder_company_code": "c0000003",
        "user_company_id": "test",  // 使用者
        "sold_date": "2020-11-06",  // 銷售日期
        "issued_date": "2020-11-06",  // 簽約日期
        "start_date": "2020-11-06",  // 合約開始
        "end_date": "2020-11-06",  // 合約到期
        "expiration_date": "2020-11-06",  // 合約終止
        "contract_month": "15",  // 合約年限
        "is_permanent": "0",  // 永久
        "is_exclusive": "0",  // 專屬
        "authorized_area_type": "1",  // 授權地區
        "authorized_area_id": "1",  // 授權地區
        "authorized_country_id": [],
        "note1": "0",  // 備註1
        "note2": "0",  // 備註2
        "note3": "0",  // 備註3
        "tax_rate": "6",
        "content": [
          {
            "id": "2",
            "cm_id": "2",
            "name": "test",
            "use_type_id": "2",
            "type": "1",
            "song_id": "7",
            "song_code": "bsc001002",
            "song_name": "不再孤單",
            "distribution_format": "1",  // 權利型態
            "contract_author_id": "8",  // 藝人合約
            "contract_author_code": "test",  // 藝人合約 code
            "flat_fee": "50",
            "syn_fee": "60",
            "mech_flat_fee": "70",
            "mech_adv": "80",
            "isrc_id": "7",
            "isrc": "TWK961600116",
            "amount": "90",
            "notes": "fk",
            "record": [
              {
                "id": "11",
                "cmc_id": "3",
                "song_right_id": null,
                "contract_song_id": null,
                "isrc_split_id": "47",
                "isrc_ratio": null,
                "contract_author_id": "91",
                "commission_id": "165",
                "author_id": "111",
                "name": "易桀齊",
                "split_type": "CD-日本",
                "split_percent": "6.000",
                "song_right_type_id": "1",
                "song_right_type_name": "詞",
                "rights_ratio": "8.333%",
              },
              {
                "id": "12",
                "cmc_id": "3",
                "song_right_id": null,
                "contract_song_id": null,
                "isrc_split_id": "46",
                "isrc_ratio": null,
                "contract_author_id": "91",
                "commission_id": "165",
                "author_id": "111",
                "name": "易桀齊",
                "split_type": "CD-日本",
                "split_percent": "6.000",
                "song_right_type_id": "2",
                "song_right_type_name": "曲",
                "rights_ratio": "5%",
              },
              {
                "id": "48",
                "cmc_id": "3",
                "song_right_id": null,
                "contract_song_id": null,
                "isrc_split_id": "46",
                "isrc_ratio": null,
                "contract_author_id": "91",
                "commission_id": "165",
                "author_id": "111",
                "name": "易桀齊",
                "split_type": "CD-日本",
                "split_percent": "6.000",
                "song_right_type_id": "1",
                "song_right_type_name": "詞",
                "rights_ratio": "8.333%",
              },
              {
                "id": "49",
                "cmc_id": "3",
                "song_right_id": null,
                "contract_song_id": null,
                "isrc_split_id": "46",
                "isrc_ratio": null,
                "contract_author_id": "91",
                "commission_id": "165",
                "author_id": "111",
                "name": "易桀齊",
                "split_type": "CD-日本",
                "split_percent": "6.000",
                "song_right_type_id": "1",
                "song_right_type_name": "詞",
                "rights_ratio": "8.333%",
              }
            ],
            "lyrics": [
              {
                "id": "9",
                "cmc_id": "3",
                "song_right_id": "20",
                "contract_song_id": "206",
                "isrc_split_id": "47",
                "isrc_ratio": "100.000%",
                "contract_author_id": null,
                "commission_id": "164",
                "author_id": "111",
                "name": "易桀齊",
                "split_type": "Mechani.-台灣",
                "split_percent": "60.000",
                "song_right_type_id": "1",
                "song_right_type_name": "詞",
                "rights_ratio": "8.333%"
              },
              {
                "id": "10",
                "cmc_id": "3",
                "song_right_id": "20",
                "contract_song_id": "206",
                "isrc_split_id": "48",
                "isrc_ratio": "100.000%",
                "contract_author_id": null,
                "commission_id": "165",
                "author_id": "111",
                "name": "易桀齊",
                "split_type": "Mechani.-台灣",
                "split_percent": "75.000",
                "song_right_type_id": "1",
                "song_right_type_name": "詞",
                "rights_ratio": "5%"
              },
              {
                "id": "46",
                "cmc_id": "3",
                "song_right_id": "20",
                "contract_song_id": "206",
                "isrc_split_id": "49",
                "isrc_ratio": "100.000%",
                "contract_author_id": null,
                "commission_id": "164",
                "author_id": "111",
                "name": "易桀齊",
                "split_type": "Mechani.-台灣",
                "split_percent": "60.000",
                "song_right_type_id": "1",
                "song_right_type_name": "詞",
                "rights_ratio": "8.333%"
              },
              {
                "id": "47",
                "cmc_id": "3",
                "song_right_id": "20",
                "contract_song_id": "206",
                "isrc_split_id": "50",
                "isrc_ratio": "100.000%",
                "contract_author_id": null,
                "commission_id": "165",
                "author_id": "111",
                "name": "易桀齊",
                "split_type": "Mechani.-台灣",
                "split_percent": "75.000",
                "song_right_type_id": "1",
                "song_right_type_name": "詞",
                "rights_ratio": "8.333%"
              }
            ]
          }
        ]
      }
    },
    "execution_time": "0.1340",
    "memory_usage": "3.84MB",
    "status_code": "00000000",
    "params": {
      "cm_id": "2"
    }
  };

  return res.json(returnObj);
}

function updateData(req, res) {
  return res.json({
    data: {
      contract_misc_id: '1'
    }
  });
}

function getContractAuthorByCode(req, res) {
  const returnObj = {
    "data": [
      {
        "contract_author": {
          "id": "10",
          "contract_code": "AA-ROCK-BD0006",
          "is_delete": "0"
        },
        "party_b_company": {
          "id": "143",
          "company_code": "c0000143",
          "name": "滾石國際音樂股份有限公司",
          "is_delete": "0"
        }
      }
    ],
    "execution_time": "0.1443",
    "memory_usage": "3.78MB",
    "status_code": "00000000",
    "params": {
      "keyword": "BD0006",
      "release_date": "2020-11-06"
    }
  };

  return res.json(returnObj);
}

function getSettleView(req, res) {
  const returnObj = {
    "data": {
      "data_list": {
        "total": 793666,
        "cnt": 49,
        "data": [
          {
            "exchange_rate": "122.00",
            "other_type": "general",
            "product_name": "test",
            "product_code": "test2",
            "cm_our_contract_code": "test",
            "product_date": "2021-02-01",
            "company_name": "Avex Taiwan Inc.",
            "use_type_name": "DVD",
            "song_code": "bsc010100",
            "author_contract_code": null,
            "song_name": "倔強",
            "isrc": null,
            "type": "flat_fee",
            "num": "123",
            "area": "tw",
            "auth_area": "TW"
          },
          {
            "exchange_rate": "122.00",
            "other_type": "general",
            "product_name": "test",
            "product_code": "test2",
            "cm_our_contract_code": "test",
            "product_date": "2021-02-01",
            "company_name": "Avex Taiwan Inc.",
            "use_type_name": "DVD",
            "song_code": "bsc010100",
            "author_contract_code": null,
            "song_name": "倔強",
            "isrc": null,
            "type": "syn_fee",
            "num": "45",
            "area": "tw",
            "auth_area": "TW"
          },
          {
            "exchange_rate": "122.00",
            "other_type": "general",
            "product_name": "test",
            "product_code": "test2",
            "cm_our_contract_code": "test",
            "product_date": "2021-02-01",
            "company_name": "Avex Taiwan Inc.",
            "use_type_name": "BD",
            "song_code": "bsc000007",
            "author_contract_code": null,
            "song_name": "五月天廣告全紀錄",
            "isrc": "TWRD16200001",
            "type": "flat_fee",
            "num": "12345",
            "area": "tw",
            "auth_area": "TW"
          },
          {
            "exchange_rate": "4.87",
            "other_type": "general",
            "product_name": "test",
            "product_code": "test3",
            "cm_our_contract_code": "test",
            "product_date": "2021-02-01",
            "company_name": "常夏音樂經紀有限公司",
            "use_type_name": "DVD",
            "song_code": "bsc010100",
            "author_contract_code": null,
            "song_name": "倔強",
            "isrc": null,
            "type": "flat_fee",
            "num": "1",
            "area": "tw",
            "auth_area": "TW"
          },
          {
            "exchange_rate": "4.87",
            "other_type": "general",
            "product_name": "test",
            "product_code": "test3",
            "cm_our_contract_code": "test",
            "product_date": "2021-02-01",
            "company_name": "常夏音樂經紀有限公司",
            "use_type_name": "DVD",
            "song_code": "bsc010100",
            "author_contract_code": null,
            "song_name": "倔強",
            "isrc": null,
            "type": "syn_fee",
            "num": "2",
            "area": "tw",
            "auth_area": "TW"
          },
          {
            "exchange_rate": "4.87",
            "other_type": "general",
            "product_name": "test",
            "product_code": "test3",
            "cm_our_contract_code": "test",
            "product_date": "2021-02-01",
            "company_name": "常夏音樂經紀有限公司",
            "use_type_name": "DVD",
            "song_code": "bsc010100",
            "author_contract_code": null,
            "song_name": "倔強",
            "isrc": null,
            "type": "mech_flat_fee",
            "num": "3",
            "area": "tw",
            "auth_area": "TW"
          },
          {
            "exchange_rate": "4.87",
            "other_type": "general",
            "product_name": "test",
            "product_code": "test3",
            "cm_our_contract_code": "test",
            "product_date": "2021-02-01",
            "company_name": "常夏音樂經紀有限公司",
            "use_type_name": "DVD",
            "song_code": "bsc010100",
            "author_contract_code": null,
            "song_name": "倔強",
            "isrc": null,
            "type": "mech_adv",
            "num": "4",
            "area": "tw",
            "auth_area": "TW"
          },
          {
            "exchange_rate": "4.87",
            "other_type": "general",
            "product_name": "test",
            "product_code": "test3",
            "cm_our_contract_code": "test",
            "product_date": "2021-02-01",
            "company_name": "常夏音樂經紀有限公司",
            "use_type_name": "APP",
            "song_code": "bsc000006",
            "author_contract_code": null,
            "song_name": "Talking of mayday",
            "isrc": null,
            "type": "flat_fee",
            "num": "11",
            "area": "tw",
            "auth_area": "TW"
          },
          {
            "exchange_rate": "4.87",
            "other_type": "general",
            "product_name": "test",
            "product_code": "test3",
            "cm_our_contract_code": "test",
            "product_date": "2021-02-01",
            "company_name": "常夏音樂經紀有限公司",
            "use_type_name": "APP",
            "song_code": "bsc000006",
            "author_contract_code": null,
            "song_name": "Talking of mayday",
            "isrc": null,
            "type": "syn_fee",
            "num": "22",
            "area": "tw",
            "auth_area": "TW"
          },
          {
            "exchange_rate": "4.87",
            "other_type": "general",
            "product_name": "test",
            "product_code": "test3",
            "cm_our_contract_code": "test",
            "product_date": "2021-02-01",
            "company_name": "常夏音樂經紀有限公司",
            "use_type_name": "DVD",
            "song_code": "bsc000011",
            "author_contract_code": null,
            "song_name": "盛夏光年長版六分鐘電影片花絮",
            "isrc": null,
            "type": "flat_fee",
            "num": "11",
            "area": "tw",
            "auth_area": "TW"
          },
          {
            "exchange_rate": "4.87",
            "other_type": "general",
            "product_name": "test",
            "product_code": "test3",
            "cm_our_contract_code": "test",
            "product_date": "2021-02-01",
            "company_name": "常夏音樂經紀有限公司",
            "use_type_name": "CD",
            "song_code": "bsc001002",
            "author_contract_code": null,
            "song_name": "不再孤單",
            "isrc": "TWK241855530",
            "type": "flat_fee",
            "num": "123",
            "area": "tw",
            "auth_area": "TW"
          },
          {
            "exchange_rate": "4.87",
            "other_type": "general",
            "product_name": "test",
            "product_code": "test3",
            "cm_our_contract_code": "test",
            "product_date": "2021-02-01",
            "company_name": "常夏音樂經紀有限公司",
            "use_type_name": "APP",
            "song_code": "bsc001006",
            "author_contract_code": null,
            "song_name": "九世戀人",
            "isrc": "TWK231855534",
            "type": "flat_fee",
            "num": "123",
            "area": "tw",
            "auth_area": "TW"
          },
          {
            "exchange_rate": "4.87",
            "other_type": "general",
            "product_name": "test",
            "product_code": "test3",
            "cm_our_contract_code": "test",
            "product_date": "2021-02-01",
            "company_name": "常夏音樂經紀有限公司",
            "use_type_name": "BD",
            "song_code": "bsc001002",
            "author_contract_code": null,
            "song_name": "不再孤單",
            "isrc": "TWK241855530",
            "type": "flat_fee",
            "num": "12345",
            "area": "tw",
            "auth_area": "TW"
          },
          {
            "exchange_rate": "4.87",
            "other_type": "general",
            "product_name": "test",
            "product_code": "test3",
            "cm_our_contract_code": "test",
            "product_date": "2021-02-01",
            "company_name": "常夏音樂經紀有限公司",
            "use_type_name": "DVD",
            "song_code": "bsc010100",
            "author_contract_code": null,
            "song_name": "倔強",
            "isrc": "TWK241900089",
            "type": "flat_fee",
            "num": "1",
            "area": "tw",
            "auth_area": "TW"
          },
          {
            "exchange_rate": "4.87",
            "other_type": "general",
            "product_name": "test",
            "product_code": "test3",
            "cm_our_contract_code": "test",
            "product_date": "2021-02-01",
            "company_name": "常夏音樂經紀有限公司",
            "use_type_name": "DVD",
            "song_code": "bsc010100",
            "author_contract_code": null,
            "song_name": "倔強",
            "isrc": "TWK241900089",
            "type": "syn_fee",
            "num": "2",
            "area": "tw",
            "auth_area": "TW"
          },
          {
            "exchange_rate": "4.87",
            "other_type": "general",
            "product_name": "test",
            "product_code": "test3",
            "cm_our_contract_code": "test",
            "product_date": "2021-02-01",
            "company_name": "常夏音樂經紀有限公司",
            "use_type_name": "DVD",
            "song_code": "bsc010100",
            "author_contract_code": null,
            "song_name": "倔強",
            "isrc": "TWK241900089",
            "type": "mech_flat_fee",
            "num": "3",
            "area": "tw",
            "auth_area": "TW"
          },
          {
            "exchange_rate": "4.87",
            "other_type": "general",
            "product_name": "test",
            "product_code": "test3",
            "cm_our_contract_code": "test",
            "product_date": "2021-02-01",
            "company_name": "常夏音樂經紀有限公司",
            "use_type_name": "DVD",
            "song_code": "bsc010100",
            "author_contract_code": null,
            "song_name": "倔強",
            "isrc": "TWK241900089",
            "type": "mech_adv",
            "num": "4",
            "area": "tw",
            "auth_area": "TW"
          },
          {
            "exchange_rate": "4.87",
            "other_type": "general",
            "product_name": "test",
            "product_code": "test3",
            "cm_our_contract_code": "test",
            "product_date": "2021-02-01",
            "company_name": "常夏音樂經紀有限公司",
            "use_type_name": "DVD",
            "song_code": "bsc010100",
            "author_contract_code": null,
            "song_name": "倔強",
            "isrc": null,
            "type": "flat_fee",
            "num": "12345",
            "area": "tw",
            "auth_area": "TW"
          },
          {
            "exchange_rate": "4.87",
            "other_type": "general",
            "product_name": "test",
            "product_code": "test3",
            "cm_our_contract_code": "test",
            "product_date": "2021-02-01",
            "company_name": "常夏音樂經紀有限公司",
            "use_type_name": "DVD",
            "song_code": "bsc010100",
            "author_contract_code": null,
            "song_name": "倔強",
            "isrc": null,
            "type": "syn_fee",
            "num": "23",
            "area": "tw",
            "auth_area": "TW"
          },
          {
            "exchange_rate": "4.87",
            "other_type": "general",
            "product_name": "test",
            "product_code": "test3",
            "cm_our_contract_code": "test",
            "product_date": "2021-02-01",
            "company_name": "常夏音樂經紀有限公司",
            "use_type_name": "DVD",
            "song_code": "bsc010100",
            "author_contract_code": null,
            "song_name": "倔強",
            "isrc": null,
            "type": "mech_flat_fee",
            "num": "3",
            "area": "tw",
            "auth_area": "TW"
          },
          {
            "exchange_rate": "4.87",
            "other_type": "general",
            "product_name": "test",
            "product_code": "test3",
            "cm_our_contract_code": "test",
            "product_date": "2021-02-01",
            "company_name": "常夏音樂經紀有限公司",
            "use_type_name": "DVD",
            "song_code": "bsc010100",
            "author_contract_code": null,
            "song_name": "倔強",
            "isrc": null,
            "type": "mech_adv",
            "num": "4",
            "area": "tw",
            "auth_area": "TW"
          },
          {
            "exchange_rate": "4.87",
            "other_type": "general",
            "product_name": "test",
            "product_code": "test3",
            "cm_our_contract_code": "test",
            "product_date": "2021-02-01",
            "company_name": "常夏音樂經紀有限公司",
            "use_type_name": "BD",
            "song_code": "bsc000006",
            "author_contract_code": null,
            "song_name": "Talking of mayday",
            "isrc": null,
            "type": "flat_fee",
            "num": "123",
            "area": "tw",
            "auth_area": "TW"
          },
          {
            "other_type": "karaoke",
            "product_name": "全放空/文慧如 ft. 鼓鼓 呂思緯",
            "product_code": "2020-040",
            "product_date": "2020-04-23",
            "company_name": "華研國際音樂股份有限公司",
            "use_type_name": "1",
            "song_code": "bsc012456",
            "type": "syn_fee",
            "num": "18000",
            "song_name": "全放空",
            "isrc": "TWD952080101",
            "exchange_rate": "1",
            "area": "tw",
            "auth_area": "TW"
          },
          {
            "other_type": "karaoke",
            "product_name": "全放空/文慧如 ft. 鼓鼓 呂思緯",
            "product_code": "2020-040",
            "product_date": "2020-04-23",
            "company_name": "華研國際音樂股份有限公司",
            "use_type_name": "1",
            "song_code": "bsc012456",
            "type": "mech_adv",
            "num": "9000",
            "song_name": "全放空",
            "isrc": "TWD952080101",
            "exchange_rate": "1",
            "area": "tw",
            "auth_area": "TW"
          },
          {
            "other_type": "karaoke",
            "product_name": "全放空/文慧如 ft. 鼓鼓 呂思緯",
            "product_code": "2020-040",
            "product_date": "2020-04-23",
            "company_name": "華研國際音樂股份有限公司",
            "use_type_name": "1",
            "song_code": "bsc012456",
            "type": "flat_fee",
            "num": "9000",
            "song_name": "全放空",
            "isrc": "TWD952080101",
            "exchange_rate": "1",
            "area": "tw",
            "auth_area": "TW"
          },
          {
            "other_type": "karaoke",
            "product_name": "傷心的人別聽慢歌(貫徹快樂)/五月天",
            "product_code": "KS-2145-13",
            "product_date": "2013-08-29",
            "company_name": "相信音樂國際股份有限公司",
            "use_type_name": "1",
            "song_code": "bsc011243",
            "type": "syn_fee",
            "num": "60000",
            "song_name": "傷心的人別聽慢歌 (貫徹快樂)",
            "isrc": "TWK241388829",
            "exchange_rate": "1",
            "area": "tw",
            "auth_area": "TW"
          },
          {
            "other_type": "karaoke",
            "product_name": "傷心的人別聽慢歌(貫徹快樂)/五月天",
            "product_code": "KS-2145-13",
            "product_date": "2013-08-29",
            "company_name": "相信音樂國際股份有限公司",
            "use_type_name": "1",
            "song_code": "bsc011243",
            "type": "mech_adv",
            "num": "30000",
            "song_name": "傷心的人別聽慢歌 (貫徹快樂)",
            "isrc": "TWK241388829",
            "exchange_rate": "1",
            "area": "tw",
            "auth_area": "TW"
          },
          {
            "other_type": "karaoke",
            "product_name": "傷心的人別聽慢歌(貫徹快樂)/五月天",
            "product_code": "KS-2145-13",
            "product_date": "2013-08-29",
            "company_name": "相信音樂國際股份有限公司",
            "use_type_name": "1",
            "song_code": "bsc011243",
            "type": "flat_fee",
            "num": "30000",
            "song_name": "傷心的人別聽慢歌 (貫徹快樂)",
            "isrc": "TWK241388829",
            "exchange_rate": "1",
            "area": "tw",
            "auth_area": "TW"
          },
          {
            "other_type": "karaoke",
            "product_name": "派對動物/五月天",
            "product_code": "KS-2341-8",
            "product_date": "2016-06-02",
            "company_name": "相信音樂國際股份有限公司",
            "use_type_name": "1",
            "song_code": "bsc011830",
            "type": "syn_fee",
            "num": "60000",
            "song_name": "派對動物",
            "isrc": "TWK241680790",
            "exchange_rate": "1",
            "area": "tw",
            "auth_area": "TW"
          },
          {
            "other_type": "karaoke",
            "product_name": "派對動物/五月天",
            "product_code": "KS-2341-8",
            "product_date": "2016-06-02",
            "company_name": "相信音樂國際股份有限公司",
            "use_type_name": "1",
            "song_code": "bsc011830",
            "type": "mech_adv",
            "num": "30000",
            "song_name": "派對動物",
            "isrc": "TWK241680790",
            "exchange_rate": "1",
            "area": "tw",
            "auth_area": "TW"
          },
          {
            "other_type": "karaoke",
            "product_name": "派對動物/五月天",
            "product_code": "KS-2341-8",
            "product_date": "2016-06-02",
            "company_name": "相信音樂國際股份有限公司",
            "use_type_name": "1",
            "song_code": "bsc011830",
            "type": "flat_fee",
            "num": "30000",
            "song_name": "派對動物",
            "isrc": "TWK241680790",
            "exchange_rate": "1",
            "area": "tw",
            "auth_area": "TW"
          },
          {
            "other_type": "karaoke",
            "product_name": "鬥陣/黃奕儒Ezu",
            "product_code": "KS-2579",
            "product_date": "2020-01-02",
            "company_name": "相信音樂國際股份有限公司",
            "use_type_name": "1",
            "song_code": "bsc001017",
            "type": "syn_fee",
            "num": "30000",
            "song_name": "鬥陣",
            "isrc": "TWEI81900012",
            "exchange_rate": "1",
            "area": "tw",
            "auth_area": "TW"
          },
          {
            "other_type": "karaoke",
            "product_name": "鬥陣/黃奕儒Ezu",
            "product_code": "KS-2579",
            "product_date": "2020-01-02",
            "company_name": "相信音樂國際股份有限公司",
            "use_type_name": "1",
            "song_code": "bsc001017",
            "type": "mech_adv",
            "num": "15000",
            "song_name": "鬥陣",
            "isrc": "TWEI81900012",
            "exchange_rate": "1",
            "area": "tw",
            "auth_area": "TW"
          },
          {
            "other_type": "karaoke",
            "product_name": "鬥陣/黃奕儒Ezu",
            "product_code": "KS-2579",
            "product_date": "2020-01-02",
            "company_name": "相信音樂國際股份有限公司",
            "use_type_name": "1",
            "song_code": "bsc001017",
            "type": "flat_fee",
            "num": "15000",
            "song_name": "鬥陣",
            "isrc": "TWEI81900012",
            "exchange_rate": "1",
            "area": "tw",
            "auth_area": "TW"
          },
          {
            "other_type": "karaoke",
            "product_name": "超機車/鼓鼓 呂思緯feat.Matzka",
            "product_code": "KS-2582",
            "product_date": "2020-01-09",
            "company_name": "相信音樂國際股份有限公司",
            "use_type_name": "1",
            "song_code": "bsc012296",
            "type": "syn_fee",
            "num": "60000",
            "song_name": "超機車",
            "isrc": "TWK241911707",
            "exchange_rate": "1",
            "area": "tw",
            "auth_area": "TW"
          },
          {
            "other_type": "karaoke",
            "product_name": "超機車/鼓鼓 呂思緯feat.Matzka",
            "product_code": "KS-2582",
            "product_date": "2020-01-09",
            "company_name": "相信音樂國際股份有限公司",
            "use_type_name": "1",
            "song_code": "bsc012296",
            "type": "mech_adv",
            "num": "30000",
            "song_name": "超機車",
            "isrc": "TWK241911707",
            "exchange_rate": "1",
            "area": "tw",
            "auth_area": "TW"
          },
          {
            "other_type": "karaoke",
            "product_name": "超機車/鼓鼓 呂思緯feat.Matzka",
            "product_code": "KS-2582",
            "product_date": "2020-01-09",
            "company_name": "相信音樂國際股份有限公司",
            "use_type_name": "1",
            "song_code": "bsc012296",
            "type": "flat_fee",
            "num": "30000",
            "song_name": "超機車",
            "isrc": "TWK241911707",
            "exchange_rate": "1",
            "area": "tw",
            "auth_area": "TW"
          },
          {
            "other_type": "karaoke",
            "product_name": "在家裡/家家",
            "product_code": "KS-2586",
            "product_date": "2020-01-16",
            "company_name": "相信音樂國際股份有限公司",
            "use_type_name": "1",
            "song_code": "bsc012248",
            "type": "syn_fee",
            "num": "30000",
            "song_name": "在家裡",
            "isrc": "TWK241911903",
            "exchange_rate": "1",
            "area": "tw",
            "auth_area": "TW"
          },
          {
            "other_type": "karaoke",
            "product_name": "在家裡/家家",
            "product_code": "KS-2586",
            "product_date": "2020-01-16",
            "company_name": "相信音樂國際股份有限公司",
            "use_type_name": "1",
            "song_code": "bsc012248",
            "type": "mech_adv",
            "num": "15000",
            "song_name": "在家裡",
            "isrc": "TWK241911903",
            "exchange_rate": "1",
            "area": "tw",
            "auth_area": "TW"
          },
          {
            "other_type": "karaoke",
            "product_name": "在家裡/家家",
            "product_code": "KS-2586",
            "product_date": "2020-01-16",
            "company_name": "相信音樂國際股份有限公司",
            "use_type_name": "1",
            "song_code": "bsc012248",
            "type": "flat_fee",
            "num": "15000",
            "song_name": "在家裡",
            "isrc": "TWK241911903",
            "exchange_rate": "1",
            "area": "tw",
            "auth_area": "TW"
          },
          {
            "other_type": "karaoke",
            "product_name": "蕭秉治 feat.五月天怪獸/痛快世代",
            "product_code": "KS-2594",
            "product_date": "2020-02-13",
            "company_name": "相信音樂國際股份有限公司",
            "use_type_name": "1",
            "song_code": "bsc012246",
            "type": "syn_fee",
            "num": "60000",
            "song_name": "痛快世代",
            "isrc": "TWK241981940",
            "exchange_rate": "1",
            "area": "tw",
            "auth_area": "TW"
          },
          {
            "other_type": "karaoke",
            "product_name": "蕭秉治 feat.五月天怪獸/痛快世代",
            "product_code": "KS-2594",
            "product_date": "2020-02-13",
            "company_name": "相信音樂國際股份有限公司",
            "use_type_name": "1",
            "song_code": "bsc012246",
            "type": "mech_adv",
            "num": "30000",
            "song_name": "痛快世代",
            "isrc": "TWK241981940",
            "exchange_rate": "1",
            "area": "tw",
            "auth_area": "TW"
          },
          {
            "other_type": "karaoke",
            "product_name": "蕭秉治 feat.五月天怪獸/痛快世代",
            "product_code": "KS-2594",
            "product_date": "2020-02-13",
            "company_name": "相信音樂國際股份有限公司",
            "use_type_name": "1",
            "song_code": "bsc012246",
            "type": "flat_fee",
            "num": "30000",
            "song_name": "痛快世代",
            "isrc": "TWK241981940",
            "exchange_rate": "1",
            "area": "tw",
            "auth_area": "TW"
          },
          {
            "other_type": "karaoke",
            "product_name": "老實情人/呂思緯 Agoo Lu",
            "product_code": "KS-2597",
            "product_date": "2020-02-20",
            "company_name": "相信音樂國際股份有限公司",
            "use_type_name": "1",
            "song_code": "bsc012300",
            "type": "syn_fee",
            "num": "30000",
            "song_name": "老實情人",
            "isrc": "TWK241911711",
            "exchange_rate": "1",
            "area": "tw",
            "auth_area": "TW"
          },
          {
            "other_type": "karaoke",
            "product_name": "老實情人/呂思緯 Agoo Lu",
            "product_code": "KS-2597",
            "product_date": "2020-02-20",
            "company_name": "相信音樂國際股份有限公司",
            "use_type_name": "1",
            "song_code": "bsc012300",
            "type": "mech_adv",
            "num": "15000",
            "song_name": "老實情人",
            "isrc": "TWK241911711",
            "exchange_rate": "1",
            "area": "tw",
            "auth_area": "TW"
          },
          {
            "other_type": "karaoke",
            "product_name": "老實情人/呂思緯 Agoo Lu",
            "product_code": "KS-2597",
            "product_date": "2020-02-20",
            "company_name": "相信音樂國際股份有限公司",
            "use_type_name": "1",
            "song_code": "bsc012300",
            "type": "flat_fee",
            "num": "15000",
            "song_name": "老實情人",
            "isrc": "TWK241911711",
            "exchange_rate": "1",
            "area": "tw",
            "auth_area": "TW"
          },
          {
            "other_type": "karaoke",
            "product_name": "超展開/鼓鼓 呂思緯",
            "product_code": "KS-2608",
            "product_date": "2020-03-26",
            "company_name": "相信音樂國際股份有限公司",
            "use_type_name": "1",
            "song_code": "bsc012239",
            "type": "syn_fee",
            "num": "30000",
            "song_name": "超展開",
            "isrc": "TWK241911704",
            "exchange_rate": "1",
            "area": "tw",
            "auth_area": "TW"
          },
          {
            "other_type": "karaoke",
            "product_name": "超展開/鼓鼓 呂思緯",
            "product_code": "KS-2608",
            "product_date": "2020-03-26",
            "company_name": "相信音樂國際股份有限公司",
            "use_type_name": "1",
            "song_code": "bsc012239",
            "type": "mech_adv",
            "num": "15000",
            "song_name": "超展開",
            "isrc": "TWK241911704",
            "exchange_rate": "1",
            "area": "tw",
            "auth_area": "TW"
          },
          {
            "other_type": "karaoke",
            "product_name": "超展開/鼓鼓 呂思緯",
            "product_code": "KS-2608",
            "product_date": "2020-03-26",
            "company_name": "相信音樂國際股份有限公司",
            "use_type_name": "1",
            "song_code": "bsc012239",
            "type": "flat_fee",
            "num": "15000",
            "song_name": "超展開",
            "isrc": "TWK241911704",
            "exchange_rate": "1",
            "area": "tw",
            "auth_area": "TW"
          }
        ]
      }
    },
    "execution_time": "0.2523",
    "memory_usage": "3.84MB",
    "status_code": "00000000",
    "params": {
      "phase_type": "1",
      "phase_id": "112",
      "agent_eid": "1"
    }
  };

  return res.json(returnObj);
}

function getLyricsStatistics(req, res) {
  const returnObj = {
    "data": {
      "total_cnt": 20,
      "total_before_tax": 276000,
      "total_actually_paid": 209100,
      "total_diff": 66900,
      "data_list": [
        {
          "product_code": "KS-2341-8",
          "product_name": "派對動物/五月天",
          "song_name": "派對動物",
          "product_type": "其他",
          "author_name": "陳信宏",
          "before_tax": "30000",
          "song_right": "詞",
          "split_ratio": "50.000",
          "tax_rate": null,
          "commission": "85.000",
          "pay_company": "相信音樂國際股份有限公司",
          "actually_paid": 25500
        },
        {
          "product_code": "KS-2341-8",
          "product_name": "派對動物/五月天",
          "song_name": "派對動物",
          "product_type": "其他",
          "author_name": "陳信宏",
          "before_tax": "30000",
          "song_right": "曲",
          "split_ratio": "50.000",
          "tax_rate": null,
          "commission": "85.000",
          "pay_company": "相信音樂國際股份有限公司",
          "actually_paid": 25500
        },
        {
          "product_code": "KS-2341-8",
          "product_name": "派對動物/五月天",
          "song_name": "派對動物",
          "product_type": "其他",
          "author_name": "陳信宏",
          "before_tax": "15000",
          "song_right": "詞",
          "split_ratio": "50.000",
          "tax_rate": null,
          "commission": "85.000",
          "pay_company": "相信音樂國際股份有限公司",
          "actually_paid": 12750
        },
        {
          "product_code": "KS-2341-8",
          "product_name": "派對動物/五月天",
          "song_name": "派對動物",
          "product_type": "其他",
          "author_name": "陳信宏",
          "before_tax": "15000",
          "song_right": "曲",
          "split_ratio": "50.000",
          "tax_rate": null,
          "commission": "85.000",
          "pay_company": "相信音樂國際股份有限公司",
          "actually_paid": 12750
        },
        {
          "product_code": "KS-2341-8",
          "product_name": "派對動物/五月天",
          "song_name": "派對動物",
          "product_type": "其他",
          "author_name": "陳信宏",
          "before_tax": "15000",
          "song_right": "詞",
          "split_ratio": "50.000",
          "tax_rate": null,
          "commission": "85.000",
          "pay_company": "相信音樂國際股份有限公司",
          "actually_paid": 12750
        },
        {
          "product_code": "KS-2341-8",
          "product_name": "派對動物/五月天",
          "song_name": "派對動物",
          "product_type": "其他",
          "author_name": "陳信宏",
          "before_tax": "15000",
          "song_right": "曲",
          "split_ratio": "50.000",
          "tax_rate": null,
          "commission": "85.000",
          "pay_company": "相信音樂國際股份有限公司",
          "actually_paid": 12750
        },
        {
          "product_code": "KS-2582",
          "product_name": "超機車/鼓鼓 呂思緯feat.Matzka",
          "song_name": "超機車",
          "product_type": "其他",
          "author_name": "王昱辰",
          "before_tax": "3000",
          "song_right": "曲",
          "split_ratio": "5.000",
          "tax_rate": "5.000",
          "commission": "70.000",
          "pay_company": "相信音樂國際股份有限公司",
          "actually_paid": 2100
        },
        {
          "product_code": "KS-2582",
          "product_name": "超機車/鼓鼓 呂思緯feat.Matzka",
          "song_name": "超機車",
          "product_type": "其他",
          "author_name": "呂國緯",
          "before_tax": "27000",
          "song_right": "詞",
          "split_ratio": "45.000",
          "tax_rate": "5.000",
          "commission": "65.000",
          "pay_company": "相信音樂國際股份有限公司",
          "actually_paid": 17550
        },
        {
          "product_code": "KS-2582",
          "product_name": "超機車/鼓鼓 呂思緯feat.Matzka",
          "song_name": "超機車",
          "product_type": "其他",
          "author_name": "呂國緯",
          "before_tax": "13500",
          "song_right": "曲",
          "split_ratio": "22.500",
          "tax_rate": "5.000",
          "commission": "65.000",
          "pay_company": "相信音樂國際股份有限公司",
          "actually_paid": 8775
        },
        {
          "product_code": "KS-2582",
          "product_name": "超機車/鼓鼓 呂思緯feat.Matzka",
          "song_name": "超機車",
          "product_type": "其他",
          "author_name": "王昱辰",
          "before_tax": "1500",
          "song_right": "曲",
          "split_ratio": "5.000",
          "tax_rate": "5.000",
          "commission": "70.000",
          "pay_company": "相信音樂國際股份有限公司",
          "actually_paid": 1050
        },
        {
          "product_code": "KS-2582",
          "product_name": "超機車/鼓鼓 呂思緯feat.Matzka",
          "song_name": "超機車",
          "product_type": "其他",
          "author_name": "呂國緯",
          "before_tax": "13500",
          "song_right": "詞",
          "split_ratio": "45.000",
          "tax_rate": "5.000",
          "commission": "65.000",
          "pay_company": "相信音樂國際股份有限公司",
          "actually_paid": 8775
        },
        {
          "product_code": "KS-2582",
          "product_name": "超機車/鼓鼓 呂思緯feat.Matzka",
          "song_name": "超機車",
          "product_type": "其他",
          "author_name": "呂國緯",
          "before_tax": "6750",
          "song_right": "曲",
          "split_ratio": "22.500",
          "tax_rate": "5.000",
          "commission": "65.000",
          "pay_company": "相信音樂國際股份有限公司",
          "actually_paid": 4387.5
        },
        {
          "product_code": "KS-2582",
          "product_name": "超機車/鼓鼓 呂思緯feat.Matzka",
          "song_name": "超機車",
          "product_type": "其他",
          "author_name": "王昱辰",
          "before_tax": "1500",
          "song_right": "曲",
          "split_ratio": "5.000",
          "tax_rate": "5.000",
          "commission": "70.000",
          "pay_company": "相信音樂國際股份有限公司",
          "actually_paid": 1050
        },
        {
          "product_code": "KS-2582",
          "product_name": "超機車/鼓鼓 呂思緯feat.Matzka",
          "song_name": "超機車",
          "product_type": "其他",
          "author_name": "呂國緯",
          "before_tax": "13500",
          "song_right": "詞",
          "split_ratio": "45.000",
          "tax_rate": "5.000",
          "commission": "65.000",
          "pay_company": "相信音樂國際股份有限公司",
          "actually_paid": 8775
        },
        {
          "product_code": "KS-2582",
          "product_name": "超機車/鼓鼓 呂思緯feat.Matzka",
          "song_name": "超機車",
          "product_type": "其他",
          "author_name": "呂國緯",
          "before_tax": "6750",
          "song_right": "曲",
          "split_ratio": "22.500",
          "tax_rate": "5.000",
          "commission": "65.000",
          "pay_company": "相信音樂國際股份有限公司",
          "actually_paid": 4387.5
        },
        {
          "product_code": "KS-2586",
          "product_name": "在家裡/家家",
          "song_name": "在家裡",
          "product_type": "其他",
          "author_name": "陳勇志",
          "before_tax": "4500",
          "song_right": "詞",
          "split_ratio": "15.000",
          "tax_rate": "5.000",
          "commission": "75.000",
          "pay_company": "相信音樂國際股份有限公司",
          "actually_paid": 3375
        },
        {
          "product_code": "KS-2586",
          "product_name": "在家裡/家家",
          "song_name": "在家裡",
          "product_type": "其他",
          "author_name": "陳勇志",
          "before_tax": "2250",
          "song_right": "詞",
          "split_ratio": "15.000",
          "tax_rate": "5.000",
          "commission": "75.000",
          "pay_company": "相信音樂國際股份有限公司",
          "actually_paid": 1687.5
        },
        {
          "product_code": "KS-2586",
          "product_name": "在家裡/家家",
          "song_name": "在家裡",
          "product_type": "其他",
          "author_name": "陳勇志",
          "before_tax": "2250",
          "song_right": "詞",
          "split_ratio": "15.000",
          "tax_rate": "5.000",
          "commission": "75.000",
          "pay_company": "相信音樂國際股份有限公司",
          "actually_paid": 1687.5
        },
        {
          "product_code": "KS-2594",
          "product_name": "蕭秉治 feat.五月天怪獸/痛快世代",
          "song_name": "痛快世代",
          "product_type": "其他",
          "author_name": "溫尚翊",
          "before_tax": "30000",
          "song_right": "曲",
          "split_ratio": "50.000",
          "tax_rate": "5.000",
          "commission": "80.000",
          "pay_company": "相信音樂國際股份有限公司",
          "actually_paid": 24000
        },
        {
          "product_code": "KS-2594",
          "product_name": "蕭秉治 feat.五月天怪獸/痛快世代",
          "song_name": "痛快世代",
          "product_type": "其他",
          "author_name": "蕭治豪",
          "before_tax": "30000",
          "song_right": "詞",
          "split_ratio": "50.000",
          "tax_rate": "5.000",
          "commission": "65.000",
          "pay_company": "相信音樂國際股份有限公司",
          "actually_paid": 19500
        }
      ]
    },
    "execution_time": "0.0748",
    "memory_usage": "3.82MB",
    "status_code": "00000000",
    "params": {
      "phase_type": "1",
      "phase_id": "112",
      "page_current": "1",
      "page_size": "20",
      "agent_eid": "1"
    }
  };

  return res.json(returnObj);
}

function getRecordStatistics(req, res) {
  const returnObj = {
    "data": {
      "total_cnt": 12,
      "total_before_tax": 2931426,
      "total_actually_paid": 249942.6,
      "total_diff": 2681483.4,
      "data_list": [
        {
          "product_code": "KS-2559",
          "product_name": "我想要的快樂/家家",
          "song_name": "我想要的快樂",
          "product_type": "其他",
          "author_name": "紀家盈",
          "before_tax": "308571",
          "song_right": "1",
          "split_ratio": "100.000",
          "tax_rate": "5.000",
          "commission": "6.000",
          "data_phase": "2019-10-01",
          "pay_company": "相信音樂國際股份有限公司",
          "actually_paid": 18514.26
        },
        {
          "product_code": "KS-2567",
          "product_name": "吾愛無愛/白安",
          "song_name": "吾愛無愛",
          "product_type": "其他",
          "author_name": "白安嚴",
          "before_tax": "308571",
          "song_right": "1",
          "split_ratio": "100.000",
          "tax_rate": "5.000",
          "commission": "6.000",
          "data_phase": "2019-10-01",
          "pay_company": "相信音樂國際股份有限公司",
          "actually_paid": 18514.26
        },
        {
          "product_code": "KS-2569",
          "product_name": "所愛之初/白安",
          "song_name": "所愛之初",
          "product_type": "其他",
          "author_name": "白安嚴",
          "before_tax": "308571",
          "song_right": "1",
          "split_ratio": "100.000",
          "tax_rate": "5.000",
          "commission": "6.000",
          "data_phase": "2019-10-01",
          "pay_company": "相信音樂國際股份有限公司",
          "actually_paid": 18514.26
        },
        {
          "product_code": "KS-2570",
          "product_name": "樂高/鼓鼓 呂思緯",
          "song_name": "樂高",
          "product_type": "其他",
          "author_name": "呂國緯",
          "before_tax": "308571",
          "song_right": "1",
          "split_ratio": "100.000",
          "tax_rate": "5.000",
          "commission": "6.000",
          "data_phase": "2019-10-01",
          "pay_company": "相信音樂國際股份有限公司",
          "actually_paid": 18514.26
        },
        {
          "product_code": "KS-2571",
          "product_name": "沒有錯/家家",
          "song_name": "沒有錯",
          "product_type": "其他",
          "author_name": "紀家盈",
          "before_tax": "308571",
          "song_right": "1",
          "split_ratio": "100.000",
          "tax_rate": "5.000",
          "commission": "6.000",
          "data_phase": "2019-10-01",
          "pay_company": "相信音樂國際股份有限公司",
          "actually_paid": 18514.26
        },
        {
          "product_code": "KS-2573",
          "product_name": "跪了/鼓鼓 呂思緯 feat.Julia 吳卓源",
          "song_name": "跪了",
          "product_type": "其他",
          "author_name": "呂國緯",
          "before_tax": "154285.5",
          "song_right": "1",
          "split_ratio": "50.000",
          "tax_rate": "5.000",
          "commission": "6.000",
          "data_phase": "2019-10-01",
          "pay_company": "相信音樂國際股份有限公司",
          "actually_paid": 9257.13
        },
        {
          "product_code": "KS-2575",
          "product_name": "最想見到你/白安",
          "song_name": "最想見到你",
          "product_type": "其他",
          "author_name": "白安嚴",
          "before_tax": "154286",
          "song_right": "1",
          "split_ratio": "100.000",
          "tax_rate": "5.000",
          "commission": "6.000",
          "data_phase": "2019-10-01",
          "pay_company": "相信音樂國際股份有限公司",
          "actually_paid": 9257.16
        },
        {
          "product_code": "KS-2578",
          "product_name": "為你變成他/蘇慧倫",
          "song_name": "為你變成他",
          "product_type": "其他",
          "author_name": "蘇慧倫",
          "before_tax": "308571",
          "song_right": "1",
          "split_ratio": "100.000",
          "tax_rate": "5.000",
          "commission": "30.000",
          "data_phase": "2020-01-01",
          "pay_company": "水晶共振股份有限公司",
          "actually_paid": 92571.3
        },
        {
          "product_code": "KS-2579",
          "product_name": "鬥陣/黃奕儒Ezu",
          "song_name": "鬥陣",
          "product_type": "其他",
          "author_name": "黃奕儒",
          "before_tax": "111429",
          "song_right": "1",
          "split_ratio": "100.000",
          "tax_rate": "5.000",
          "commission": "6.000",
          "data_phase": "2020-01-01",
          "pay_company": "相信音樂國際股份有限公司",
          "actually_paid": 6685.74
        },
        {
          "product_code": "KS-2582",
          "product_name": "超機車/鼓鼓 呂思緯feat.Matzka",
          "song_name": "超機車",
          "product_type": "其他",
          "author_name": "呂國緯",
          "before_tax": "154285.5",
          "song_right": "1",
          "split_ratio": "50.000",
          "tax_rate": "5.000",
          "commission": "6.000",
          "data_phase": "2020-01-01",
          "pay_company": "相信音樂國際股份有限公司",
          "actually_paid": 9257.13
        },
        {
          "product_code": "KS-2583",
          "product_name": "不想認輸/家家",
          "song_name": "不想認輸",
          "product_type": "其他",
          "author_name": "紀家盈",
          "before_tax": "308571",
          "song_right": "1",
          "split_ratio": "100.000",
          "tax_rate": "5.000",
          "commission": "6.000",
          "data_phase": "2020-01-01",
          "pay_company": "相信音樂國際股份有限公司",
          "actually_paid": 18514.26
        },
        {
          "product_code": "KS-2586",
          "product_name": "在家裡/家家",
          "song_name": "在家裡",
          "product_type": "其他",
          "author_name": "紀家盈",
          "before_tax": "197143",
          "song_right": "1",
          "split_ratio": "100.000",
          "tax_rate": "5.000",
          "commission": "6.000",
          "data_phase": "2020-01-01",
          "pay_company": "相信音樂國際股份有限公司",
          "actually_paid": 11828.58
        }
      ]
    }
  };

  return res.json(returnObj);
}

export default {
  'get   /contract_misc': getList,
  'get   /contract_misc/view': getInfo,
  'put   /contract_misc': updateData,
  'patch /contract_misc': updateData,
  'get   /contract_misc/contracts_author_by_code': getContractAuthorByCode,
  'post  /contract_misc': updateData,
  'patch /contract_misc/settle_phase': updateData,
  'get   /contract_misc/settle_view': getSettleView,
  'get   /contract_misc/lyrics_statistics_search': getLyricsStatistics,
  'get   /contract_misc/record_statistics_search': getRecordStatistics
}